version: '2'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample site from https://startbootstrap.com/template-overviews/agency/

services:
  proxy:
    build:
      context: .  # setting the current directory as the path to use
      dockerfile: nginx.Dockerfile
    image: nginx-reverse-proxy-custom # naming the custom image
    ports:
      - '18080:80'
  web:
    image: httpd
    volumes:
      - ./html:/usr/local/apache2/htdocs/