# create your drupal and postgres config here, based off the last assignment
version: '2'

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-drupal
    ports:
      - '18080:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=supers3cret
    volumes:
      - pgsql-data:/var/lib/postgresql/data
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  pgsql-data: